language: node_js
node_js: 
  - 16
env:
  global:
    - CLOUD_RUN_REGION=us-west1
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1   # prevent gcloud from prompting
before_install:
  - openssl aes-256-cbc -K $encrypted_e442d0c98a17_key -iv $encrypted_e442d0c98a17_iv -in som-rit-ourvoice-travis.json.enc -out som-rit-ourvoice-travis.json -d
  - gcloud auth activate-service-account --key-file=som-rit-ourvoice-travis.json
  - gcloud auth configure-docker        # enable "docker push" to gcr
  - gcloud config set project "som-rit-ourvoice"
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
script:
  - gcloud version || true
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  # Add gcloud to $PATH
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud version
  - |
    set -ex;
    npm run build && \
    gcloud app deploy app.yaml \
    set +x